import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-media-royalty-participation-audit",
  "engine": "recovery",
  "title": "Media Royalty & Participation Audit",
  "shortTitle": "Royalty Recovery OS",
  "tagline": "Reconstruct exploitation revenue and collect unpaid creator, licensor, and participant royalties",
  "industry": "Media Rights Financial Assurance",
  "uiPort": 4569,
  "apiPort": 5569,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Contractually owed royalties and participation income identified and collected",
  "valueNarrative": "Connect rights agreements, title and asset metadata, exploitation reports, platform statements, revenue, deductions, recoupment, and payments.",
  "calculation": {
    "actualKey": "paidRoyalty",
    "expectedKey": "expectedRoyalty",
    "actualLabel": "Royalty or participation paid",
    "expectedLabel": "Contract-expected amount",
    "varianceLabel": "Potential royalty recovery",
    "direction": "expected-minus-actual",
    "finding": "Rights, exploitation, revenue, deduction, recoupment, and payment evidence indicate unpaid royalty or participation income.",
    "actions": [
      "Validate rights scope, territory, term, and exploitation data",
      "Reconstruct gross receipts and allowable deductions",
      "Apply royalty, escalator, recoupment, and participation terms",
      "Issue audit claim and reconcile payment"
    ]
  }
},[
feature("rights-and-contract-library","RRO01","Rights and contract library","Reconcile rights and contract library using rights agreements, title metadata, cue sheets, exploitation reports, platform statements, revenue, deductions, recoupment, reserves, and payments.","Produce a governed rights and contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["distributor","Distributor / Licensee","text","Global Stream Media"],["workPeriod","Work / Period","text","TITLE-884 / 2026-H1"],["paidRoyalty","Royalty Paid","currency",864000],["expectedRoyalty","Contract-Expected Royalty","currency",1125000]],{amountField:"paidRoyalty",subjects:["Music catalog royalty","Film profit participation","Podcast license","Publishing royalty","Streaming distribution agreement"]}),
feature("work-title-and-asset-registry","RRO02","Work title and asset registry","Reconcile work title and asset registry using rights agreements, title metadata, cue sheets, exploitation reports, platform statements, revenue, deductions, recoupment, reserves, and payments.","Produce a governed work title and asset registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["distributor","Distributor / Licensee","text","Global Stream Media"],["workPeriod","Work / Period","text","TITLE-884 / 2026-H1"],["paidRoyalty","Royalty Paid","currency",864000],["expectedRoyalty","Contract-Expected Royalty","currency",1125000]],{amountField:"paidRoyalty",subjects:["Music catalog royalty","Film profit participation","Podcast license","Publishing royalty","Streaming distribution agreement"]}),
feature("exploitation-report-ingestion","RRO03","Exploitation report ingestion","Reconcile exploitation report ingestion using rights agreements, title metadata, cue sheets, exploitation reports, platform statements, revenue, deductions, recoupment, reserves, and payments.","Produce a governed exploitation report ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["distributor","Distributor / Licensee","text","Global Stream Media"],["workPeriod","Work / Period","text","TITLE-884 / 2026-H1"],["paidRoyalty","Royalty Paid","currency",864000],["expectedRoyalty","Contract-Expected Royalty","currency",1125000]],{amountField:"paidRoyalty",subjects:["Music catalog royalty","Film profit participation","Podcast license","Publishing royalty","Streaming distribution agreement"]}),
feature("platform-statement-normalization","RRO04","Platform statement normalization","Reconcile platform statement normalization using rights agreements, title metadata, cue sheets, exploitation reports, platform statements, revenue, deductions, recoupment, reserves, and payments.","Produce a governed platform statement normalization decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["distributor","Distributor / Licensee","text","Global Stream Media"],["workPeriod","Work / Period","text","TITLE-884 / 2026-H1"],["paidRoyalty","Royalty Paid","currency",864000],["expectedRoyalty","Contract-Expected Royalty","currency",1125000]],{amountField:"paidRoyalty",subjects:["Music catalog royalty","Film profit participation","Podcast license","Publishing royalty","Streaming distribution agreement"]}),
feature("territory-and-rights-validation","RRO05","Territory and rights validation","Reconcile territory and rights validation using rights agreements, title metadata, cue sheets, exploitation reports, platform statements, revenue, deductions, recoupment, reserves, and payments.","Produce a governed territory and rights validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["distributor","Distributor / Licensee","text","Global Stream Media"],["workPeriod","Work / Period","text","TITLE-884 / 2026-H1"],["paidRoyalty","Royalty Paid","currency",864000],["expectedRoyalty","Contract-Expected Royalty","currency",1125000]],{amountField:"paidRoyalty",subjects:["Music catalog royalty","Film profit participation","Podcast license","Publishing royalty","Streaming distribution agreement"]}),
feature("gross-receipts-reconstruction","RRO06","Gross receipts reconstruction","Reconcile gross receipts reconstruction using rights agreements, title metadata, cue sheets, exploitation reports, platform statements, revenue, deductions, recoupment, reserves, and payments.","Produce a governed gross receipts reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["distributor","Distributor / Licensee","text","Global Stream Media"],["workPeriod","Work / Period","text","TITLE-884 / 2026-H1"],["paidRoyalty","Royalty Paid","currency",864000],["expectedRoyalty","Contract-Expected Royalty","currency",1125000]],{amountField:"paidRoyalty",subjects:["Music catalog royalty","Film profit participation","Podcast license","Publishing royalty","Streaming distribution agreement"]}),
feature("deduction-and-distribution-fee-audit","RRO07","Deduction and distribution-fee audit","Reconcile deduction and distribution-fee audit using rights agreements, title metadata, cue sheets, exploitation reports, platform statements, revenue, deductions, recoupment, reserves, and payments.","Produce a governed deduction and distribution-fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["distributor","Distributor / Licensee","text","Global Stream Media"],["workPeriod","Work / Period","text","TITLE-884 / 2026-H1"],["paidRoyalty","Royalty Paid","currency",864000],["expectedRoyalty","Contract-Expected Royalty","currency",1125000]],{amountField:"paidRoyalty",subjects:["Music catalog royalty","Film profit participation","Podcast license","Publishing royalty","Streaming distribution agreement"]}),
feature("royalty-rate-and-escalator-calculation","RRO08","Royalty rate and escalator calculation","Reconcile royalty rate and escalator calculation using rights agreements, title metadata, cue sheets, exploitation reports, platform statements, revenue, deductions, recoupment, reserves, and payments.","Produce a governed royalty rate and escalator calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["distributor","Distributor / Licensee","text","Global Stream Media"],["workPeriod","Work / Period","text","TITLE-884 / 2026-H1"],["paidRoyalty","Royalty Paid","currency",864000],["expectedRoyalty","Contract-Expected Royalty","currency",1125000]],{amountField:"paidRoyalty",subjects:["Music catalog royalty","Film profit participation","Podcast license","Publishing royalty","Streaming distribution agreement"]}),
feature("advance-and-recoupment-ledger","RRO09","Advance and recoupment ledger","Reconcile advance and recoupment ledger using rights agreements, title metadata, cue sheets, exploitation reports, platform statements, revenue, deductions, recoupment, reserves, and payments.","Produce a governed advance and recoupment ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["distributor","Distributor / Licensee","text","Global Stream Media"],["workPeriod","Work / Period","text","TITLE-884 / 2026-H1"],["paidRoyalty","Royalty Paid","currency",864000],["expectedRoyalty","Contract-Expected Royalty","currency",1125000]],{amountField:"paidRoyalty",subjects:["Music catalog royalty","Film profit participation","Podcast license","Publishing royalty","Streaming distribution agreement"]}),
feature("reserve-and-release-validation","RRO10","Reserve and release validation","Reconcile reserve and release validation using rights agreements, title metadata, cue sheets, exploitation reports, platform statements, revenue, deductions, recoupment, reserves, and payments.","Produce a governed reserve and release validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["distributor","Distributor / Licensee","text","Global Stream Media"],["workPeriod","Work / Period","text","TITLE-884 / 2026-H1"],["paidRoyalty","Royalty Paid","currency",864000],["expectedRoyalty","Contract-Expected Royalty","currency",1125000]],{amountField:"paidRoyalty",subjects:["Music catalog royalty","Film profit participation","Podcast license","Publishing royalty","Streaming distribution agreement"]}),
feature("cross-collateralization-review","RRO11","Cross-collateralization review","Reconcile cross-collateralization review using rights agreements, title metadata, cue sheets, exploitation reports, platform statements, revenue, deductions, recoupment, reserves, and payments.","Produce a governed cross-collateralization review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["distributor","Distributor / Licensee","text","Global Stream Media"],["workPeriod","Work / Period","text","TITLE-884 / 2026-H1"],["paidRoyalty","Royalty Paid","currency",864000],["expectedRoyalty","Contract-Expected Royalty","currency",1125000]],{amountField:"paidRoyalty",subjects:["Music catalog royalty","Film profit participation","Podcast license","Publishing royalty","Streaming distribution agreement"]}),
feature("royalty-statement-audit","RRO12","Royalty statement audit","Reconcile royalty statement audit using rights agreements, title metadata, cue sheets, exploitation reports, platform statements, revenue, deductions, recoupment, reserves, and payments.","Produce a governed royalty statement audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["distributor","Distributor / Licensee","text","Global Stream Media"],["workPeriod","Work / Period","text","TITLE-884 / 2026-H1"],["paidRoyalty","Royalty Paid","currency",864000],["expectedRoyalty","Contract-Expected Royalty","currency",1125000]],{amountField:"paidRoyalty",subjects:["Music catalog royalty","Film profit participation","Podcast license","Publishing royalty","Streaming distribution agreement"]}),
feature("licensee-claim-and-response","RRO13","Licensee claim and response","Reconcile licensee claim and response using rights agreements, title metadata, cue sheets, exploitation reports, platform statements, revenue, deductions, recoupment, reserves, and payments.","Produce a governed licensee claim and response decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["distributor","Distributor / Licensee","text","Global Stream Media"],["workPeriod","Work / Period","text","TITLE-884 / 2026-H1"],["paidRoyalty","Royalty Paid","currency",864000],["expectedRoyalty","Contract-Expected Royalty","currency",1125000]],{amountField:"paidRoyalty",subjects:["Music catalog royalty","Film profit participation","Podcast license","Publishing royalty","Streaming distribution agreement"]}),
feature("payment-and-receivable-reconciliation","RRO14","Payment and receivable reconciliation","Reconcile payment and receivable reconciliation using rights agreements, title metadata, cue sheets, exploitation reports, platform statements, revenue, deductions, recoupment, reserves, and payments.","Produce a governed payment and receivable reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["distributor","Distributor / Licensee","text","Global Stream Media"],["workPeriod","Work / Period","text","TITLE-884 / 2026-H1"],["paidRoyalty","Royalty Paid","currency",864000],["expectedRoyalty","Contract-Expected Royalty","currency",1125000]],{amountField:"paidRoyalty",subjects:["Music catalog royalty","Film profit participation","Podcast license","Publishing royalty","Streaming distribution agreement"]}),
feature("catalog-licensee-and-channel-analytics","RRO15","Catalog licensee and channel analytics","Reconcile catalog licensee and channel analytics using rights agreements, title metadata, cue sheets, exploitation reports, platform statements, revenue, deductions, recoupment, reserves, and payments.","Produce a governed catalog licensee and channel analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["distributor","Distributor / Licensee","text","Global Stream Media"],["workPeriod","Work / Period","text","TITLE-884 / 2026-H1"],["paidRoyalty","Royalty Paid","currency",864000],["expectedRoyalty","Contract-Expected Royalty","currency",1125000]],{amountField:"paidRoyalty",subjects:["Music catalog royalty","Film profit participation","Podcast license","Publishing royalty","Streaming distribution agreement"]})
]);
